document.write("<h3>PJ par archétype</h3>");
document.write("<h4>Les combattants</h4>");
document.write("<h4>Les magiciens</h4>");
document.write("<nav class='menu'>");
document.write("<a href='./Barol.html'>Barol</a>");
document.write("<a href='./LalianVess.html'>Lalian Vess</a>");
document.write("</nav>");
document.write("<h4>Les inclassables</h4>");
document.write("<nav class='menu'>");
document.write("<a href='./Lora.html'>Lora</a>");
document.write("</nav>");