document.write("<h3>Navigation rapide</h3>");
document.write("<nav class='menu'>");
document.write("<a href='./magie.html'>La magie dans lyrium</a>");
document.write("<p class='eg'>Page non crée (domaines et types de magiciens)</p>");
document.write("<a href='#'>La magie au quotidien</a>");
document.write("<p class='eg'>Page non crée (test de lancement de sorts)</p>");
document.write("</nav>");
document.write("<h3>Création de sorts</h3>");
document.write("<nav class='menu'>");
document.write("<a href='./theories.html'>Dissection d'un sort</a>");
document.write("<p class='eg'>Où l'on apprend tout de la théorie des media et des différentes classes de sorts.</p>");
document.write("<a href='#'>L'intensité d'un sort</a>");
document.write("<p class='eg'>Page non crée</p>");
document.write("<a href='./calculateur_intensites.html'>Calculateur d'intensités</a>");
document.write("<p class='eg'>Parce que c'est rudement plus pratique d'estimer rapidement le coût d'un sort sur un champ de bataille</p>");
document.write("</nav>");
document.write("<h3>La convocation</h3>");
document.write("<nav class='menu'>");
document.write("<a href='#'>Théorie de la convocation</a>");
document.write("<p class='eg'>Page non crée</p>");
document.write("<a href='#'>Noyaux de convocation</a>");
document.write("<p class='eg'>Page non crée</p>");
document.write("</nav>");