document.write("<h3>Navigation rapide</h3>");
document.write("<nav class='menu'>");
document.write("<a href='./personnage.html'>Page principale</a>");
document.write("<a href='./competences.html'>Les compétences</a>");
document.write("<a href='./talents.html'>Les talents</a>");
document.write("</nav>");
document.write("<h3>Création et évolution</h3>");
document.write("<nav class='menu'>");
document.write("<a href='./gen_personnage.html'>Générateur de personnage</a>");
document.write("<a href='./PJ/HUB.html'>Liste des personnages créés</a>");
document.write("<a href='./experience.html'>Expérience et gain de niveau</a>");
document.write("</nav>");